# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
source:           ./templates
destination:      ./_gh_pages
#layouts:     ./docs/_layouts

exclude:          [".editorconfig", ".gitignore", ".project",
 ".classpath", "pom.xml", ".ruby-version", "bower.json", "composer.json", "reload.js", "preview*.html",
 "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js",
 "package.json", "node_modules", "README.md", "docs", "run", "wiki", "src","fontello" ]
port:             3000

# Custom vars
version:          "(0.1.0)"
repo:             "https://github.com/imaguiraga/bootstrap-css-customizer"
github_url:       "https://github.com/imaguiraga/bootstrap-css-customizer"
github_user_url: "https://github.com/imaguiraga"
bootswacth_url: "http://bootswatch.com"
