# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
#source:           ./docs
#layouts:     ./docs/_layouts

exclude:          [".editorconfig", ".gitignore", ".project",
 ".classpath", "pom.xml", ".ruby-version", "bower.json", "composer.json", 
 "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js",
 "package.json", "node_modules", "README.md", "less", "docs", "run", "wiki", "src" ]
port:             9001

# Custom vars
repo:             todo

